export const englishLetters = "abcdefghijklmnopqrstuvwxyz".toUpperCase().split('');
export const gameWords = [
  "Blood",
  "Refactor",
  "Developer",
  "Algorithm",
  "Compile",
  "Variable",
  "Function",
  "Debugger",
  "Framework",
  "Module",
  "Interface",
  "Object",
  "Pointer",
  "Syntax",
  "Package",
  "Binary",
  "Loop",
  "Thread",
  "Array",
  "Stack",
  "Queue",
  "Protocol",
  "Cache",
  "Runtime",
  "Plugin",
  "Script",
  "Class",
  "Method",
  "Constructor",
  "Database",
  "Repository",
  "Version",
  "Branch",
  "Commit",
  "Server",
  "Client",
  "Network",
  "Session",
  "Token",
  "Command",
];

export function getRandomWord() {
  return gameWords[Math.floor(Math.random() * gameWords.length)].toUpperCase();
}
